name: Lint and Test

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Run Lint
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
