name: Packaging

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  packaging:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run:  cargo build --release
      - name: Rename Packaging File
        run:  cp target/release/auto-installer auto-installer-${{ matrix.os }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: auto-installer-${{ matrix.os }}
